### ISSUE TITLE
Update to 0.19.0 fails

### ISSUE THREAD

**Issue by michaelaye** [samu/git-diff-details#26]
> oniguruma@4.2.2 install /private/var/folders/tt/k11390b92vl_dygt4m0s7gjr008bbb/T/apm-install-dir-11572-69316-1s6vasl/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/tt/k11390b92vl_dygt4m0s7gjr008bbb/T/apm-install-dir-11572-69316-1s6vasl/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/klay6683/.atom/.apm/.apmrc" "--userconfig" "/Users/klay6683/.atom/.apmrc" "install" "/private/var/folders/tt/k11390b92vl_dygt4m0s7gjr008bbb/T/d-11572-69316-1h1h8dv/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! file /Users/klay6683/.atom/.apm/property-accessors/1.1.3/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /Users/klay6683/.atom/.apm/property-accessors/1.1.3/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/tt/k11390b92vl_dygt4m0s7gjr008bbb/T/apm-install-dir-11572-69316-1s6vasl/npm-debug.log

My system: OSX 10.10.4, Atom 1.0.3

**Comment by samu** [comment]
Duplicate to #23

**Comment by samu** [comment]
@michaelaye Could you please try the following (according to [this issue](https://github.com/atom/node-oniguruma/issues/18)):

`PYTHON=python2 apm install git-diff-details`

**Comment by michaelaye** [comment]
yes that worked. but note that I had to install python2 to do this, as i exclusively work with Python 3, so that can't be the solution.

**Comment by samu** [comment]
@michaelaye thanks for the feedback.
