### ISSUE TITLE
Installing git-diff-details@0.20.0 failed

### ISSUE THREAD

**Issue by jschrab** [samu/git-diff-details#29]
I'm having Atom fail to install 0.20.0 (the "npm-debug.log" file mentioned in the dump does not exist):

> oniguruma@4.2.2 install /private/var/folders/80/0rfz1jwj7_xgvb07bz46qn0w0000gp/T/apm-install-dir-11577-6338-7lybzf/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild

npm ERR! Darwin 14.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/JSchrab/.atom/.apm/.apmrc" "--userconfig" "/Users/JSchrab/.atom/.apmrc" "install" "/private/var/folders/80/0rfz1jwj7_xgvb07bz46qn0w0000gp/T/d-11577-6338-uuugjh/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! oniguruma@4.2.2 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the oniguruma@4.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/80/0rfz1jwj7_xgvb07bz46qn0w0000gp/T/apm-install-dir-11577-6338-7lybzf/npm-debug.log

**Comment by samu** [comment]
#23
