### ISSUE TITLE
Allow selecting text inside diff

### ISSUE THREAD

**Issue by UltCombo** [samu/git-diff-details#30]
Would it be possible to select and copy text inside the diff view?
Pressing the "copy" button, then pasting it somewhere and selecting just what I want is rather cumbersome.

**Comment by samu** [comment]
@UltCombo Sounds like a good idea. I'm very busy with other things though, so this is probably not coming in the near future, unless someone else gives it a shot.

**Comment by samu** [comment]
This is fixed thanks to #51. It is available in `v1.2.0`, which is compatible only with atom version `1.7.0`.
