### ISSUE TITLE
Blocks Esc on fuzzy files search!

### ISSUE THREAD

**Issue by nardev** [samu/git-diff-details#32]
It overrides Esc for closing fuzzy files search. Should not do that i think!!!

On Debian

**Comment by samu** [comment]
@nardev thanks for reporting

**Comment by ProLoser** [comment]
@samu actually blocks escape almost everywhere. I can't escape the find-replace, I can't escape the command palette. It's really problematic.

**Comment by samu** [comment]
@nardev  @ProLoser sorry for not looking into this sooner.

I tried to reproduce it on my system and couldn't. 

* What does your keybindings resolver say? 
* Do you have any config in your keybindings that could fuck this up?

You might also want to debug this yourself. Escape is programmed in a way that if the diff panel isn't opened, it bypasses it: https://github.com/samu/git-diff-details/blob/472c5f81285f6272a7f43e8185490ad28703c666/lib/housekeeping.coffee#L27

You can debug it by cloning this repo, running `apm link -d` and then starting atom in dev mode: `atom -d`

**Comment by geksilla** [comment]
Hi @samu, I have same problem on Ubuntu. Here keybinding resolver output:

![atom_key_resolver](https://cloud.githubusercontent.com/assets/3911882/10669479/a07b1fee-78e9-11e5-8766-f8a82155f2d0.png)

**Comment by MaximSokolov** [comment]
Same problem on Ubuntu, Atom v1.0.19.
Web Inpector's console said that package has incompatible native module. Rebuiding modules solved the problem (red bug icon in status bar -> "Rebuild modules" button).

**Comment by geksilla** [comment]
@MaximSokolov, thanks! After rebuild operation all works fine.

**Comment by samu** [comment]
Thanks @MaximSokolov for the clarification.

So to anyone facing this issue: make sure the package built correctly.

**Comment by adrianomitre** [comment]
Rebuilding does not work for me.
I am running Atom 1.2.1 on Ubuntu 14.04.3.
