### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by rm-code** [samu/git-diff-details#34]
![screenshot 2015-09-25 17 58 42](https://cloud.githubusercontent.com/assets/11627131/10105468/25ec8d02-63af-11e5-9c16-aea72fbca5ce.png)

Haven't tried rebuilding the packages as I am not sure about the consequences.

**Comment by samu** [comment]
@rm-code i saw this message too a while ago and i didn't have any problems. Have you tried in the meantime?

**Comment by rm-code** [comment]
@samu 
When I activate your package it causes this issue: https://github.com/atom/find-and-replace/issues/544

**Comment by samu** [comment]
@rm-code please have a look at #32. That problem should be fixed if you successfully rebuild the package. If you can't rebuild the package, please look at #23. You might need to install additional build tools (for example python or Visual Studio if you're on windows). Sorry about that...

**Comment by rm-code** [comment]
I'll see what I can do. Thanks @samu!
