### ISSUE TITLE
Popup with diff is transparent and overlaps with a line at bottom

### ISSUE THREAD

**Issue by dyatlov** [samu/git-diff-details#4]
atom version 0.172
your plugin version: 0.5.0

![2015-01-14 13 15 59](https://cloud.githubusercontent.com/assets/360998/5737959/86802382-9bef-11e4-8933-25e30f1d3349.png)

**Comment by samu** [comment]
Thanks for reporting this. I'll take a look at this as soon as possible, for now what you could try is change the css in your own stylesheet.

**Comment by dyatlov** [comment]
thanks, added `background-color: #000` to outer style.
Other problems:
 * it's not possible to copy just part of text from old version
 * it's not handy to hide the window - need to press once again alt+g alt+d. Would be nice to react to Esc key

**Comment by mathieucivel** [comment]
+1 Esc or click to close the window

**Comment by samu** [comment]
https://github.com/atom/highlights/issues/20

**Comment by samu** [comment]
fixed with #11 and #12
