### ISSUE TITLE
Can't install package on my Win 7 Atom install

### ISSUE THREAD

**Issue by teaman** [samu/git-diff-details#40]
Here is the repeated error I get:

Installing “git-diff-details@0.21.0” failed.Hide output…

> oniguruma@5.1.2 install C:\Users\BRUCE~1.HOL\AppData\Local\Temp\apm-install-dir-116015-14728-34d9av\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild

C:\Users\BRUCE~1.HOL\AppData\Local\Temp\apm-install-dir-116015-14728-34d9av\node_modules\git-diff-details\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\bruce.holm\AppData\Local\atom\app-1.4.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\bruce.holm\\AppData\\Local\\atom\\app-1.4.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\bruce.holm\\AppData\\Local\\atom\\app-1.4.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\bruce.holm\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\bruce.holm\\.atom\\.apmrc" "install" "C:\\Users\\BRUCE~1.HOL\\AppData\\Local\\Temp\\d-116015-14728-kvvyxx\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

**Comment by samu** [comment]
please check out #23
