### ISSUE TITLE
Add staging a diff

### ISSUE THREAD

**Issue by projedi** [samu/git-diff-details#43]
There's an undo command and to complement it would be great to have a command for staging a diff to the index, so you don't have to leave the editor to do `git add -p`.

**Comment by samu** [comment]
Thanks for your suggestion. The problem with this is that we'd need to interact with git to enable it. Retrieving the diffs is something that is done through the `git-utils` package, it provide a specific api to get the line diffs. However, that package doesn't cover a wide range of git functionality. This means that i'd have to directly interact with git, similarly to [what the git-plus package does](https://github.com/akonwi/git-plus/blob/v5.13.0/lib/git.coffee#L51). In my opinion, this is out of the scope of this package. Maybe you want to suggest this feature over at the `git-plus` package?

**Comment by projedi** [comment]
Ah, I see. Turns out `git-plus` already has the feature called "Stage Hunk". Also see https://github.com/akonwi/git-plus/issues/388 Thanks for pointing it out!
