### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mark-hahn** [samu/git-diff-details#46]
0.23.0 isn't working for me.  I disabled `git-open` so the keys showed up properly in the resolver.  Now when I do `alt-g`, `alt-d`, nothing happens.  I tried inserted and deleted text.

Ubuntu 14.0.4
atom 1.5.4

**Comment by samu** [comment]
If there are no errors it's a bit hard to guess what's going on. Have you tried the latest version (`1.0.0` available for atom `1.6.0`)?

**Comment by mark-hahn** [comment]
I updated to atom 1.6.0 and git-diff-details to 1.0.0.  When I use `alt-g
alt-d` I see the keybinding in the resolver, nothing in the console, and
nothing happens in the file.

Are there any debug statements you want me to try?

**Comment by samu** [comment]
There are no debug statements. I'm afraid the only thing you can do is debugging it yourself, as you seem to be the first one encountering this and i have no idea how to reproduce this on my machine.

**Comment by samu** [comment]
Did you find a solution to this?

**Comment by mark-hahn** [comment]
I haven't had a chance.  I'm still using my git-diff-popup for now.

**Comment by samu** [comment]
Ok i see, i'll close this for now.

**Comment by samu** [comment]
@mark-hahn this should now be fixed in `1.3.0`
