### ISSUE TITLE
Alt+U keyboard shortcut doesn't undo due to conflict

### ISSUE THREAD

**Issue by ricardograca** [samu/git-diff-details#47]
That shortcut seems to be taken by `encoder-selector:show`.

Ubuntu 15.04
Atom 1.6.0

**Comment by samu** [comment]
You'll have to fix that in your keybindings file. Look for `unset!` in the atom docs.

**Comment by ricardograca** [comment]
The encoder thing is part of the standard Atom distribution, so I guess this affects all Linux users. Are you saying that everybody that wants to use this package in Linux has to manually override the keyboard shortcut?

I've looked at the [encoding-selector repo](https://github.com/atom/encoding-selector/blob/master/keymaps/encoding-selector.cson) and it seems that they decided to use a different keyboard shortcut for Linux for some reason. I'll open an issue there.
