### ISSUE TITLE
OSX alt key types special characters

### ISSUE THREAD

**Issue by sksea** [samu/git-diff-details#55]
alt+u resolves to a special character ¨ (interpreted by atom as accented A) on OSX. Any ideas?

**Comment by samu** [comment]
What do you see see in the key bindings resolver?

Also, maybe you can fix it by putting this into your keybindings file:

`
'.editor':
  'alt-u': 'native!'
`

**Comment by sksea** [comment]
Tried the snippet to no avail.

![image](https://cloud.githubusercontent.com/assets/11454733/14590921/9a3a5970-04d4-11e6-88a2-59c8cdcaf49a.png)
This is the symbol OSX inserts for alt+u. Unfortunately, I'm not sure how to screen capture atom's keybindings resolver. On OSX, holding down the alt/option key will insert special characters as shown below. 
![image](https://cloud.githubusercontent.com/assets/11454733/14590951/ba03026a-04d5-11e6-99f8-014bd46f0adc.png)

I couldn't find a simple way to disable this behavior on OSX's side either. Surprised no one else has ran into it.

Thanks

**Comment by samu** [comment]
Closing this as it isn't directly related to the package.

**Comment by Anima-t3d** [comment]
I have the same issue on mac with english keyboard. alt+u -> `¨` and alt+c -> `¸`

I would say it is related to your package as your keybindings are not taking into account mac OS:
> FYI, absolutely no keybindings should be bound to Alt on Macintosh - it is the compose character for many international keyboards.  

> Here is how it should work:

> - Anything that is Ctrl-Something on PC should be Command (META) -Something on mac
> - Anything that is Alt-Something on PC should be Ctrl-something on mac

Source: [Netbeans  alt keybindings are completly broken on MAC](https://netbeans.org/bugzilla/show_bug.cgi?id=77129#c3)
