### ISSUE TITLE
Lost old vs current versions

### ISSUE THREAD

**Issue by lbenet** [samu/git-diff-details#59]
I've been using for a while git-diff-details on a daily basis. Yet, after some upgrade, which I can not tell if it related directly to git-diff-details, atom, or even another atom package, I've lost the possibility of having *both*, the old and the new version, appearing one below the other. Do you have any idea of the problem, or if it is a conflict with a package? I am running atom 1.7.3, on OSX 10.9.5.
Thanks for helping.

**Comment by samu** [comment]
I'm not sure what you mean by old/current version. Are you saying the diff view is not showing up at all?

**Comment by lbenet** [comment]
Yes, that is what I mean: I only get highlighted the current version; before, it was possible to compare with the old/previous version.

**Comment by samu** [comment]
This was addressed in #57. Are you sure you are running the latest version? Do you see any errors in the console? What do you see in the keybindings resolver?

**Comment by lbenet** [comment]
This is the output of `atom --version`:
```
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
and this are the community packages I have installed in atom:
```
Community Packages (13) /Users/benet/.atom/packages
├── git-diff-details@1.3.0
├── ink@0.4.4
├── julia-client@0.4.7
├── language-fortran@2.0.11
├── language-gnuplot-atom@0.2.0
├── language-julia@0.6.0
├── language-latex@0.6.1
├── language-weave@0.2.4
├── latex@0.32.0
├── latex-completions@0.3.1
├── latexer@0.3.0
├── latextools@0.8.0
└── minimap@4.23.4
```
So I am using the last version. From the keybindings resolver I get what expected: ^g+^d yields a line referring to git-diff-details. I don't know how to see for any errors in the console...

**Comment by lbenet** [comment]
In the console, I got a couple of messages referring to `latextools`, and the line:
```
/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:983 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.```

**Comment by samu** [comment]
@lbenet I'll close this due to inactivity, let me know if this is still a problem.

**Comment by lbenet** [comment]
It's good to close it. I think it was/is related with some incompatibility with a latex package. I simply solved it deleting everything and reinstalling, without the latex package.
