### ISSUE TITLE
Clarify that keyboard shortcuts must be pressed in succession

### ISSUE THREAD

**Issue by Nateowami** [samu/git-diff-details#63]
It took me quite awhile to realize that I needed to press <kbd>Alt+G</kbd> and then <kbd>Alt+D</kbd>. Seeing that the shortcut was <kbd>alt-g alt-d</kbd> I assumed it either one could be used (since usually keyboard shortcuts do not silently change state, i.e., pressing one does not usually affect the next keypress, unless the UI changed in some way). Instead I was left believing <kbd>Alt+G</kbd> did nothing, and <kbd>Alt+D</kbd> frustratingly deleted text. Perhaps this could be clarified in the readme?

On a related note, like many others I didn't realize the cursor needed to be on a line that had changed. Is there a reason that despite many reports of people not understanding this, that it is not documented in the readme (the first place I looked for instructions, but found none)?

I'd be happy to create a pull request with this added. Thoughts?

**Comment by samu** [comment]
@Nateowami thanks for the suggestions.

About the short cut: i'll think about adding this to the readme. The reason why it isn't documented currently is that there are other keybindings like this in atom (for example <kbd>ctrl-k ctrl-b</kbd> for toggling the tree view) and i assumed that this type of short cut is common across the atom community. I guess you're right though to mention this specifically, as i do understand your initial frustration about the plugin.

I completely agree with your second point. Please note #62 which suggests to solve the issue by showing an alert message.

**Comment by Nateowami** [comment]
@samu That makes sense. I think adding to the readme a short description of what it does would be helpful. I installed this envisioning a GitHub-like unified diff, and when it wasn't that I was confused. Perhaps mention that it displays "diff snippets" or something?

**Comment by samu** [comment]
This is now documented properly in the readme.
