### ISSUE TITLE
Cannot read property 'length' of null in data-manager.coffee:90 for unversioned/new files

### ISSUE THREAD

**Issue by bentolor** [samu/git-diff-details#65]
Hello there!

This plugin seems to be throw an error in Atom 1.11.2 if applied on newly created files. This seems to be related to #61

## Steps to reproduce – case 1

1. Open Atom in a Git repository
2. Create a new file `foo.txt`
3. Toggle Git diff details

## Steps to reproduce – case 2
1. Step 1 & 2 from above
2. Add file to Git stash
3. Do more edits in the file
4. Toggle Git diff details

**Comment by samu** [comment]
Thanks for reporting @bentolor, this is now fixed through #64
