### ISSUE TITLE
No copy for removed fragment

### ISSUE THREAD

**Issue by nicothin** [samu/git-diff-details#66]
I deleted the text.
I see the diff.
I can not copy text from the remote fragment shown.
:(

**Comment by nicothin** [comment]
- delete any test
- press `Alt-g-d`
- show deleted line
- select part of the deleted text
- press `Ctrl-c`
- press `Ctrl-v`

The same line will be inserted where the cursor is located.
Сopied line with the cursor, not the selection of the text previously remote.

**Comment by samu** [comment]
@nicothin 

Thanks for the clarification. 

Ctrl-C is overridden by git-diff-details and is supposed to work as you describe it: Ctrl-C copies the contents of the entire diff (and Ctrl-U reverts the diff). I do understand that this causes confusion in your case though. Please note that you should be able to copy the selected text with right-click -> copy.

I'm not sure how to solve this properly. You could certainly try to override the default behaviour of git-diff-details in your keymaps, then you should be able to use Ctrl-C as you expect. Let me know if that's a suitable solution.
