### ISSUE TITLE
Question about releasing forked project as different pkg

### ISSUE THREAD

**Issue by t9md** [samu/git-diff-details#75]
Hi @samu, thanks for creating this pkg, and sorry for my mistake for PR.

Recently, I've been doing experiment based on your pkg.

https://github.com/t9md/git-diff-details

During experiment I've rewritten code very aggressively.
In early phase of experiment, I was trying to make it compatible to your pkg in case I send PR afterward.
But I gave up just because I couldn't handle my confusion to think new feature / compatibility simultaneously.

Now code and feature become very different from original pkg, I don't think you are happy to merge this.

### Question

- Do you have any opinion to release forked project as different pkg?(releasing as `inline-git-diff`).
- If you never mind, I will do
  - To avoid repeating mistake to send PR to your repo, create `inline-git-diff` project with keeping original git history.
  - publish it to atom.io

### Difference from original git-diff-details pkg

- No config options
- Cleaner inner-line diff(word diff)
- Show all diffs in editor, always instead of just showing diff at cursor
- Show added diff as well as modified, deleted diff
- Rename undo command to revert
- Can revert added diff
- Activate on toggle

**Comment by samu** [comment]
@t9md thanks for letting me know!

I agree, it would be better to release it as a different package. I don't have any problems with that!

By the way, thanks for all your other packages, i'm a big fan 👍 😄

**Comment by t9md** [comment]
Thanks for your kindness!
And thanks for creating this nice package!

**Comment by t9md** [comment]
Hi samu, I've just released fork project here

https://atom.io/packages/inline-git-diff

Also making vim-mode-plus's `maximize-pane` command compatible with your's and my-fork pkg.

https://github.com/t9md/atom-vim-mode-plus/pull/1014

Thanks again!
